theme: minima
title: Byte me, I'm a software engineer
author: vlytvynchyk
description: Welcome! This is my personal blog, where I share my experiences and insights from my journey as a software engineer. 